### ISSUE TITLE
Change the type of markdown parser according to response

### ISSUE THREAD

**Issue by komalahire** [navgurukul/bhanwari-devi#113]
1. Code examples highlighted of python courses are not showing except for some courses,  according to my understanding, the response from the backend of markdown has been changed.
Before we were getting the type of languages from markdown, but now everything is coming inside the markdown, there is no specific key for language.

2. Some courses are not responsive in phone view and in desktop view, after implementing the visualizer for code examples.

@nilshah98

**Comment by nilshah98** [comment]
Hi Komal,

Aap mujhe ye issue replicate karne ke liye steps bata sakte ho ?

1. Which URL does highlighting not work for ?
2. What steps should I follow to replicate this ? Phone pe koi link kholu, fir kuch click karu, kaise ?

**Comment by nilshah98** [comment]
1. After looking into it, I realized that this is not an issue, and rather a different response from backend API. If the `data.type` is `python` or `javascript` the syntax highlighting works. For other data types it does not.
2. Need more concrete examples and replication details for the same.

Closing this for now.
