### ISSUE TITLE
Issues while parsing HTML with Mardown

### ISSUE THREAD

**Issue by nilshah98** [navgurukul/bhanwari-devi#114]
**Context :** 
- Currently in our API response for course content, we receive it as a mixture of HTML and Markdown.
- We parse the same and display it, example - [Python Loops](https://www.merakilearn.org/course/83/exercise/3372)

**Issue :** 
- At times there is a mixture of HTML and Markdown, and depending on what is parsed first, it might have various outputs.
- Owing to this, we have an issue for - [Python Class Structure](https://www.merakilearn.org/course/152/exercise/3718)
- In the above page, there is an API response as -
```
* [`Variables`\n](https://www.merakilearn.org/course/102/exercise/3335)\n*
```
- Here, if Markdown is parsed first, and then HTML is parsed, it will all show well. Since, first it will generate the link using markdown, and then style it.
- But if, HTML is parsed first, it will insert a new line, and then when markdown process it, since it encounters the new line, it won't understand it as a string.
- And if you look at the documentation for `react-markdown` library under it's [architecture](https://github.com/remarkjs/react-markdown#architecture), you can see that it first parses as HTML and then as markdown.
- Hence, the above link causes an issue.

**Solutions :** 
- The API response should instead be -
```
* [`Variables`](https://www.merakilearn.org/course/102/exercise/3335)\n*
```
- Here, it will parse \`Variables\` with the backticks (`) but, it will just generate the same letters again just with different font. This won't have an issue with markdown parsing, as it is just the same character in different font.

**Resources :**
- The component that uses this is [ExerciseContent](https://github.com/navgurukul/bhanwari-devi/tree/main/src/components/Course/Content/ExerciseContent)
- Library used - [react-markdown](https://github.com/remarkjs/react-markdown)

**Comment by nilshah98** [comment]
CC @abhishekgupta92 @pysaquib @komalahire

**Comment by abhishekgupta92** [comment]
@pysaquib can you discuss with @nilshah98 on how feasible it is to update the response being mindful of the constraints pointed in the thread.

**Comment by nilshah98** [comment]
I can see that the data is pulled from here - https://github.com/navgurukul/newton/blob/master/instructions-to-python-facilitators/python-class-structure.md
But, I do not see the `\n` in content there, or the extra HTML signing.

**Comment by nilshah98** [comment]
- Fixed by updating the API response and removing the new line characters `\n`
