### ISSUE TITLE
To not display all answers while clicking 1 specific solution button in courses

### ISSUE THREAD

**Issue by komalahire** [navgurukul/bhanwari-devi#121]
https://user-images.githubusercontent.com/43803182/127151210-558aad1d-a1aa-4932-8661-617554485a9c.mp4

@nilshah98   In all courses, when we click on 'show solution' for 1 question, answers are getting displayed for all questions everywhere in the course.

**Comment by nilshah98** [comment]
Hi,
The issue is, that the same component is being used for different exercises, so it is never really unmounted, and hence the state is never reset.
I will try to push a solution tomorrow.

Also, please try to use the templates when creating issues.
