### ISSUE TITLE
New message notification in chat room

### ISSUE THREAD

**Issue by Poonam-Singh-Bagh** [navgurukul/bhanwari-devi#166]
**Is your feature request related to a problem? Please describe.**
Students don't get to know when they have a class or got a new message

**Describe the solution you'd like**
A badge should be displayed every time when a new message arrives with its counts.

**Additional context*
![Screenshot from 2021-10-07 12-24-16](https://user-images.githubusercontent.com/67674096/136334372-e50b66f2-bdd9-42b3-bae4-577af33ea113.png)
*
The message notification feature should look like this.
@nilshah98 @komalahire

**Comment by nilshah98** [comment]
Hi, abhi taak kya kya try kia aap logon ne ?
Kuch bata sakte ho ?
