### ISSUE TITLE
Add CSS-in-JS support

### ISSUE THREAD

**Issue by tarun-dugar** [navgurukul/bhanwari-devi#48]
- what solution to use (css modules, styled-components, emotion)
- bundling of styles
- provision to add global styles

**Comment by nilshah98** [comment]
Hi @tarun-dugar I was trying to get to pace with this issue.
But the current styles are too heavy and everything is written from scratch, so porting will require a lot of effort.
I wanted to ask do the benefits of this, outweigh the effort we are putting in?

_I am new to CSS-in-JS, so I might be missing something._

Thoughts ?
