### ISSUE TITLE
Content Drawer In course Content

### ISSUE THREAD

**Issue by kartiks26** [navgurukul/bhanwari-devi#584]

**Comment by kartiks26** [comment]
![image](https://user-images.githubusercontent.com/84696578/185177112-3ed6706c-6290-4b71-8434-0579825787b5.png)
For Class why Its getting downward?

**Comment by kartiks26** [comment]
![image](https://user-images.githubusercontent.com/84696578/185178245-a6a22d78-4bfd-4e22-a363-927b0bc8b3fc.png)
Fix this Scroll Bar

**Comment by kartiks26** [comment]
![image](https://user-images.githubusercontent.com/84696578/185178612-074fc991-a6d3-4c15-ae2a-900ebac50614.png)
Avoid Inline Styles
Look How its done elsewhere

**Comment by kartiks26** [comment]
Look Why Its getting hide here keep height small and then restrict
![image](https://user-images.githubusercontent.com/84696578/185181068-ab001cdc-2cd2-4339-ab4c-f5f032e3cc50.png)

**Comment by itsomkathe** [comment]
Above changes have been completed.
Refer to recent commits in #583 
@kartiks26

**Comment by kartiks26** [comment]
https://user-images.githubusercontent.com/84696578/185573250-b8ed6842-3372-4c3a-ac09-28a8b0a7596f.mp4

Clicking on last one gets scrolled to top

**Comment by kartiks26** [comment]
Also The Top 
![image](https://user-images.githubusercontent.com/84696578/185573438-5e8de9d3-5adc-42d6-9aec-1d458e7d81b0.png)
Dont get changed , That I will Do

**Comment by kartiks26** [comment]
@itsomkathe 
Can you look into this scroll thing
As soon as You complete just ping me

**Comment by kartiks26** [comment]
![image](https://user-images.githubusercontent.com/84696578/185573942-25698139-3fd6-4d55-8634-d314603fc8b8.png)
Look for spacing in mocup

**Comment by itsomkathe** [comment]
We need to change the entire structure of file for that. As of now, the drawer gets re-rendered every time the exercise changes. @kartiks26

**Comment by kartiks26** [comment]
@itsomkathe tried fixing both things 
test them once you are free

**Comment by saquibaijaz** [comment]
@kartiks26 Please fix this issue.
Clicking on any item in the content list makes it move randomly; it shouldn't.

https://user-images.githubusercontent.com/111858763/200571887-9c86ae55-d0dd-438d-b49b-c8c834356124.mp4

**Comment by itsomkathe** [comment]
@saquibaijaz, that's actually what he wanted. When we click on some of the last items, it scrolls so that the item moves to the middle of the list.

**Comment by saquibaijaz** [comment]
@itsomkathe 
First, all the items will not be able to move to the middle. Items at the very top and bottom will never move to the middle.
Secondly, as shown in the attached video, we want it to stay.

https://user-images.githubusercontent.com/111858763/200760262-70a82cf6-c9d3-40ba-8246-572a650c1d95.mp4

Cc: @amansharmma

**Comment by saquibaijaz** [comment]
https://user-images.githubusercontent.com/111858763/200769482-004ef9e1-f9f1-48eb-a7f5-16b17008135e.mp4

https://user-images.githubusercontent.com/111858763/200769498-72ce175d-f713-4a6f-b5e5-24e1a7e5043f.mp4

@itsomkathe @amansharmma 
Please check out these videos too. 
On the desktop, using chrome, the mobile view works fine, but now working correctly on the phone.

**Comment by kartiks26** [comment]
@saquibaijaz  This issue is faced by many people
https://github.com/mui/material-ui/issues/16942
https://user-images.githubusercontent.com/16666234/106383439-02bd2200-63d7-11eb-8f2b-b76bc426d3cb.mp4

**Comment by kartiks26** [comment]
not got any updates from official documents
will need to use the other component but it will might restrict swipeable close

**Comment by kartiks26** [comment]
If we tend to use same component we can make its position left or right still it will work
