### ISSUE TITLE
Team Page MObile view

### ISSUE THREAD

**Issue by amansharmma** [navgurukul/bhanwari-devi#590]
Fixed mobile responsiveness in Meraki Team page

**Comment by amansharmma** [comment]
Modify Meraki team page mobile version.
![Screenshot from 2022-08-18 11-58-57](https://user-images.githubusercontent.com/42709018/185310446-54cec2fd-526d-4fde-9cb1-b707d54c61fe.png)

![Screenshot from 2022-08-18 11-59-01](https://user-images.githubusercontent.com/42709018/185310533-fa64e3fc-4265-4586-8b77-53e5172b7d6e.png)

**Comment by kartiks26** [comment]
@amansharmma Link Pull request created
