### ISSUE TITLE
WhatsApp Redirection

### ISSUE THREAD

**Issue by itsomkathe** [navgurukul/bhanwari-devi#592]
On the introduction page, when clicked on the phone number, it should be redirected to WhatsApp.
[Click Here](https://drive.google.com/file/d/1HhJ7Dp4R9yPpc7xEIA3tiwelA9G2NlyB/view) for the video.

**Refer Sheet:**
TC for Landing page without login (website), Test Case 10.2
&
Student is logged in (website), Test Case 16.2

**Comment by saquibaijaz** [comment]
Sheet:
TC for Landing page without login (website), Test Case 10.2
