### ISSUE TITLE
Student role problem in Vercel

### ISSUE THREAD

**Issue by Poonam-Singh-Bagh** [navgurukul/bhanwari-devi#603]
In Vercel the student role  is not working fine.
I have an empty role list but still it showing class tab in the header and it also redirecting to /class route.

1. localhost Screenshot
![Screenshot from 2022-08-24 13-25-54](https://user-images.githubusercontent.com/67674096/186366765-ebf3ce40-5334-443b-90fe-c6398762d1a5.png)

2. Production Screenshot
![Screenshot from 2022-08-24 13-26-14](https://user-images.githubusercontent.com/67674096/186366932-2d5c20ca-75dd-43d3-8b00-7e2112e82525.png)

3. Vercel Screenshot
![Screenshot from 2022-08-24 13-26-27](https://user-images.githubusercontent.com/67674096/186367026-bf07d7b1-3531-408e-a9e9-4209e22e0e23.png)

**Comment by kartiks26** [comment]
@Poonam-Singh-Bagh if this is not happening in The main website we should not worry about this IG
