### ISSUE TITLE
(Student) Dashboard section

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#604]
**Describe the bug**
If all the courses are enrolled out, then also on the Dashboard, the unenrolled courses are shown.

**To Reproduce**
1. Login as a student
2. Enroll for a course if not already enrolled
3. Goto Dashboard
4. The dashboard should show the enrolled courses
5. Unenroll out of all the courses
6. Goto Dashboard
7. The dashboard still shows the courses that were previously enrolled

**Expected behaviour**
After unenrolling out of all the courses, the Dashboard should show the Learning Track.

**Screencast**
https://drive.google.com/file/d/1MHuwtTst_kq1CDM2l3fd5qYfbm8l-8oL/view

**Refer Sheet**
"Student is logged in (website)", Test Case 5

**Comment by Poonam-Singh-Bagh** [comment]
@saquibaijaz ongoing course (dashboard) has no link with batch. Clicking on the ongoing course card will redirect you to the course you were doing.
