### ISSUE TITLE
(Student) Invalid Name in the profile section

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#605]
**Describe the bug**
Student enters an invalid name or leaves the name field blank in the profile sction.

**To Reproduce**
1. Student edits profile and enters an invalid name, e.g. 1234, ^%$^$*
2. Student clicks on "Save profile"
3. The invalid name gets saved

**Expected behaviour**
An error message is shown asking Student to enter a Valid Name

**Screencast**
https://drive.google.com/file/d/1SCrpQoSfa_o_SwzvtxDbfGHzSGGTyIv_/view

**Refer Sheet**
Student is logged in (website), Test Case 9.4

**Comment by Poonam-Singh-Bagh** [comment]
@saquibaijaz It's also handled by the frontend. Have made the changes.

**Comment by saquibaijaz** [comment]
The special characters should be allowed, in case the student wants to enter the name in Hindi
