### ISSUE TITLE
(Student) Blank Name in the profile section

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#606]
**Describe the bug**
Student leaves the name field blank in the profile section and clicks save profile.

**To Reproduce**
1. Student edits profile and leaves the name field blank
2. Student clicks on "Save Profile"
3. The profile page gets displayed and in place of the name, the "Please Wait..." message keeps showing

**Expected behaviour**
An error message is shown asking the student to enter a name.

**Screencast**
https://drive.google.com/file/d/14i9gY-HZAQP14hfCH-YR-DScMxwE8lwp/view

**Refer Sheet**
Student is logged in (website), Test Case 9.5

**Comment by Poonam-Singh-Bagh** [comment]
@saquibaijaz It's handled by the frontend. Have made the changes.

**Comment by saquibaijaz** [comment]
https://user-images.githubusercontent.com/111858763/204781559-50e753d6-3518-438e-98a8-97deff9c8af8.mp4

@Poonam-Singh-Bagh 
Please put a check n the length of a name. Reasonable and acceptable names should not exceed 70 characters.
![image](https://user-images.githubusercontent.com/111858763/204780943-019bf29c-c910-44fd-9768-6cf9849bd5b0.png)

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh 
This can be ignored for now, but later on, a check should be imposed on the length of the name.
