### ISSUE TITLE
Exercise Navigation Scrollable

### ISSUE THREAD

**Issue by itsomkathe** [navgurukul/bhanwari-devi#608]
We have to make the exercise navigation (check at `/course-content`) scrollable. 
For reference, check out this [link](https://merakilearn.slack.com/files/U020JD76STF/F03UT8KAQUC/smooth_scrolling_menu.mkv?origin_team=T01N1V0GHGV&origin_channel=D03PEAFF3M5). We need to make it as YouTube has for topics. 

![Capture](https://user-images.githubusercontent.com/34516916/186376724-343768d4-ade0-4d7d-b730-f69df5e633e3.PNG)

**Comment by kartiks26** [comment]
@itsomkathe it looks like when we are on extreme left it shouldn't be visible and on extreme right as well

**Comment by kartiks26** [comment]
increase scrollable power on clicking it arrow by some amount

**Comment by kartiks26** [comment]
@itsomkathe  also review it from narendra once
