### ISSUE TITLE
(Student) Enter English alphabets in the mobile number field

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#610]
**Describe the bug**
Student tries to enter english alphabets in the mobile number field

**To Reproduce**
1. Student clicks on NG Admissions options in the Profile Icon Menu on the top right
2. Letter "e" can be typed in the mobile number field

**Expected behaviour**
Student should not be able to enter the alphabets as it is a Number Only box

**Screencast**
https://drive.google.com/file/d/1oM3lUFFI0Xo73_Zc94MkGYIWB7UJjwiI/view

**Refer Sheet:**
Student is logged in (website), Test Case 10.8

**Comment by komalahire** [comment]
@saquibaijaz  Not using this page anymore.

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh 
All right, I'll talk with the requirement team and will let you know if this page needs to be removed

**Comment by saquibaijaz** [comment]
The issue is on a page which is not being used on the website anymore, so closing this issue
