### ISSUE TITLE
(Student) Mobile number input box

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#611]
**Describe the bug**
Increment/Decrement text box instead of Number input box to enter mobile number

**Input box present**
Increment/Decrement box

**Input box expected**
Number input box

**Screencast**
https://drive.google.com/file/d/1gGqPQkP8kzugV3RgWENe7Trja2q3Xk8p/view

**Refer Sheet:**
Student is logged in (website), Test Case 10.9

**Comment by jschanker** [comment]
Can't access the screencast, but if this is on the Admissions page, it's a regression as it was fixed by using a `tel` type input (https://github.com/navgurukul/bhanwari-devi/pull/229#discussion_r790177114).

**Comment by saquibaijaz** [comment]
@jschanker please give me your NavGurukul email address and I'll give you access to the sheet.

**Comment by saquibaijaz** [comment]
https://user-images.githubusercontent.com/111858763/186420393-b68ff1d6-c35c-443a-b7a6-8a3a1fdd76f4.mp4

You can watch the video here. @jschanker 
This is still not fixed

**Comment by jschanker** [comment]
@saquibaijaz Thanks, I'm able to see the video now. I think after it had been fixed, it was broken in a commit in which we started using MUI (https://github.com/navgurukul/bhanwari-devi/commit/3355579c1f3f510cce1019158ba6b95cf9b83104).

**Comment by komalahire** [comment]
@saquibaijaz  Not using this page anymore.

**Comment by saquibaijaz** [comment]
This page is not available on the website anymore, so closing this issue
