### ISSUE TITLE
(Student) Click on Upcoming Classes after enrolling for Python course

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#614]
**Describe the bug**
Clicking on upcoming classes does not open the first module of the course

**To Reproduce**
1. Student enrolls for Python course
2. Student clicks on Upcoming classes
3. The first item is not highlighted and not displayed

**Expected behavior**
First module of class is displayed with the first option in the navbar highlighted and the content is displayed for that respective item

**Screencast**
https://drive.google.com/file/d/1kNZFiX-o3Q21_gYB_3ZZN27VJON-M_Ds/view

**Refer Sheet:**
Student is logged in (website), Test Case 13.6

**Comment by Poonam-Singh-Bagh** [comment]
This is happening so that the student can go directly to the option where he can join the class.
