### ISSUE TITLE
(Student) Can leave chat room after enrolling for a course

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#615]
**Describe the bug**
student is able to leave the chat room for an enrolled course

**To Reproduce**
1. Student enrolls for a course
2. Student goes to Mentor Section from the main navbar
3. Student clicks on the three-dot menu of the chat room and clicks on Leave Room
4. Student is able to leave the chat room and after the page is refreshed, the chat room for enrolled course disappears

**Expected behavior**
Student is not able to leave the chat room for an enrolled course

**Screencast**
https://drive.google.com/file/d/1csSzoPwutsEydbcry-DIAh1ORMSNnX5C/view

**Refer Sheet:**
Student is logged in (website), Test Case 13.8

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh , I cannot test it as there are no courses to enroll for.

**Comment by Poonam-Singh-Bagh** [comment]
@saquibaijaz the design has been changed now, and in new design user doesn't have the option to leave the room.
