### ISSUE TITLE
(Student) Click anywhere outside the Leave Room Option

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#617]
**Describe the bug**
Clicking anywhere outside the Leave Room option should make the option disappear, but it does not happen

**To Reproduce**
1. Go to Mentor section from the main navbar
2. Click on the three-dot menu for any of the available rooms. Leave Room option appears
3. click anywhere outside of the Leave Room option
4. The leave room option does not disappear

**Expected behaviour**
The leave room option should disappear

**Screencast**
https://drive.google.com/file/d/1I7kWS7MOmdK1MD2LR9ilVW3ZzKe55FV7/view

**refer Sheet:**
Student is logged in (website), Test Case 13.15

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh , not working

**Comment by Poonam-Singh-Bagh** [comment]
@saquibaijaz the design has been changed now, and in new design user doesn't have the option to leave the room.

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh 
I'll check the new design, then we'll close this issue

**Comment by saquibaijaz** [comment]
The issue is for a feature (CHAT ROOM) which will be changed completely, so closing this issue.
