### ISSUE TITLE
Remove moment in favour of date-fns

### ISSUE THREAD

**Issue by tarun-dugar** [navgurukul/bhanwari-devi#62]
Moment.js is on its way to deprecation. Let's replace it with date-fns.

**Comment by nilshah98** [comment]
Hi @tarun-dugar, @pysaquib can you guys confirm the date format which we are using ?

As far as I can guess by looking at the frontend code, we are using date and time from HTML forms and the follow the below formats -
Date - `YYYY-MM-DD`
Time - `HH:mm`

As for the backend, we are sending it to them as - `YYYY-MM-DDTHH:mm:ss` and adding `Z` at the end
And we are using `ISOString` in backend so removing the `Z` ?

If so, I can start to port to `date-fns`
