### ISSUE TITLE
Switch Views dropdown doesn't open on hover

### ISSUE THREAD

**Issue by jschanker** [navgurukul/bhanwari-devi#657]
**Describe the bug**
If a user has more than two roles and their browser window's width is at least 768 pixels so that Switch Views appears in the header, hovering over the text results in an error instead of the dropdown menu appearing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Affects develop only from fix https://github.com/navgurukul/bhanwari-devi/pull/645 for bug where tapping the Switch Views menu on a touchscreen in the content drawer didn't open it. @saquibaijaz : I think it'd be useful to add test cases for hovering over and clicking the Switch Views text in the various cases.

**Comment by saquibaijaz** [comment]
I'll check it out. Plans are underway to change the dashboard designs, and I am waiting for the new dashboard designs
@jschanker

**Comment by jschanker** [comment]
@saquibaijaz Sounds good, just a note that since the PR to fix this has been merged, you won't be able to see this bug on bhanwari-devi anymore. In general, I think we should add test cases for the requirements of any added feature to prevent the need for manual re-testing of stuff that previously worked when changes to the code are made.

**Comment by saquibaijaz** [comment]
@jschanker Sure. I'll see to it.
