### ISSUE TITLE
Local storage bug for Volunteer flow

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#681]
**Describe the bug**
The steps traversed by a user are stored in local storage, and if another user uses the same computer/browser to go through Volunteer flow, then the steps previously traversed are marked as done for the new user as well.

**To Reproduce**
1. Login to Volunteer flow
2. Complete a few steps
3. Logout and login as a different user
4. The steps completed for the previous user will be marked done for the new user as well

**Expected behaviour**
New users logging in for the first time should be shown the steps from the beginning, even if logged in on the same computer

**Screenshots**
https://drive.google.com/file/d/1xsIxdI6uZ6fejmeekbB6grHn8TvZXvZl/view?usp=sharing

**Refer Sheet**
Weekly Testing Bugs, Test Case 3

**Comment by komalahire** [comment]
@saquibaijaz This issue has been done. Please check.

**Comment by saquibaijaz** [comment]
@komalahire 
It's working fine
