### ISSUE TITLE
Links on the website are not working as expected

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#688]
**Describe the bug**
The links on the website are opening on the same tab. This way the user loses track of where he was on the Meraki website. The back button is also not redirecting the user to the previous page

**To Reproduce**
1. User clicks different links
2. Links are opened in the same tabs
3. User clicks the back button to revisit the previous page
4. The previous page is blank and appears only when the page is refreshed

**Expected behaviour**
The links should open in a new tab

**Screencast**
https://drive.google.com/file/d/18iLkBjvAR8j9u6U51mFchwDBp0gAgf5_/view?usp=sharing

**Refer Sheet**
TestCases for Assessment (website), Test Case 18

**Comment by komalahire** [comment]
@saquibaijaz This issue has been done. Please check.

**Comment by saquibaijaz** [comment]
@komalahire 
It's working fine
