### ISSUE TITLE
The question page is blinking

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#689]
Reported on Slack by Shahbaz Mukhtar Sheikh

**Describe the bug**
The questions page inside the assessment section blinks twice when visited using the assessment navbar

**To Reproduce**
1. User visits any course module
2. User clicks on any question icon in the assessment navbar
3. The question page appears and blinks twice

**Expected behaviour**
No blinking should be there

**Screencast**
https://drive.google.com/file/d/1O_kfSJABqm2gwZ1T3f5lLBV5OkXPon1y/view?usp=sharing

**Refer Sheet**
TestCases for Assessment (website), Test case 19

**Comment by saquibaijaz** [comment]
@kartiks26 The issue is still there

**Comment by kartiks26** [comment]
The dev server is not being updated . We have fixed it in local.
The deployment are failing
@saquibaijaz

**Comment by saquibaijaz** [comment]
All right
Let me know when it's done. Till then, can you please re-open the issue? I'll test and close it if I find it working as expected.
@kartiks26

**Comment by kartiks26** [comment]
The dev server is not being updated . We have fixed it in local.
The deployment are failing

**Comment by kartiks26** [comment]
Sure

**Comment by saquibaijaz** [comment]
@kartiks26 
Need update on this
cc: @Poonam-Singh-Bagh

**Comment by Poonam-Singh-Bagh** [comment]
Not working. Will let you know once it gets fixed.
