### ISSUE TITLE
Partners' websites not opening

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#702]
**Describe the bug**
The websites of the partners mentioned on the Partners pages are not opening for some of the partners

**To Reproduce**
1. Click on the "Our Partners" page from the footer
2. Click on the website option to visit a particular partner's website

**Expected behaviour**
Websites should open for all partners

**Screenshot**
https://drive.google.com/file/d/1n1h22dRh5DUUMotyv7-fvAFU7RkmTCwv/view?usp=sharing

**Refer Sheet**
TC for Landing page without login (website), Test Case 12.2

**Comment by kartiks26** [comment]
@saquibaijaz 
![image](https://user-images.githubusercontent.com/84696578/191091959-0d5ea87d-1803-47bf-90ee-54bace89fdf4.png)
The backend dont have links for all . need to done by backend .

**Comment by kartiks26** [comment]
@kirithiv2000

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh & @kirithiv2000 

1. Nirantar Trust/ Bihar (https://www.nirantar.net/)
2. Feminist Approach to Technology (https://www.fat-net.org/)
3. Anantmool (https://anantmool.org/)
4. iPartner India, Rajasthan -> Use the same Website as iPartner India, New Delhi
5. iPartner India (Roshni) -> Use the same website as iPartner India New Delhi
6. Arya Kanya Vidyalaya, Punjab -> They does not have a website, so we can leave it.
