### ISSUE TITLE
Assessment progress tracking

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#750]
1. The progress tracking should be done seamlessly across website and app

**Comment by Poonam-Singh-Bagh** [comment]
This should be fixed from backend side.

**Comment by Poonam-Singh-Bagh** [comment]
Result API in Assessment is responding late. @kirithiv2000 will assign the task when anyone gets free from their current task.

**Comment by kirithiv2000** [comment]
the api is taking only less than 200ms.
I dont understand why you are calling the same api 5 times.
![Screenshot from 2022-10-23 15-28-05](https://user-images.githubusercontent.com/52394696/197386053-6e63a87b-4708-4d1a-8c15-d86bcc0822e4.png)
![Screenshot from 2022-10-23 15-28-34](https://user-images.githubusercontent.com/52394696/197386039-69ab3201-caf3-4d0e-b10e-1ca203927f87.png)![image](https://user-images.githubusercontent.com/52394696/197385873-812e4a6b-6c0b-408e-b6cb-3aa9308e3f9a.png)

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh 
Check this out
![bhanwari-devi vercel app_pathway_1 (1)](https://user-images.githubusercontent.com/111858763/203774007-7a748de1-9f6a-4dbe-9eaa-c28e447df471.png)
