### ISSUE TITLE
Questions and Study Material not getting "Marked as Done" as expected

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#761]
1. The study material does not get "Marked as done" if we click NEXT for the first time. We either need to click NEXT again, click BACK, or close the module and then go to the same module; then only it is marked as done

2. The question, if answered correctly on the first attempt or after retry, or even if we see the explanation does not get the question "Marked as done", we need to click NEXT or BACK or go out of the course module and then come back, then only it is "Marked as done".

The expected behaviour is:

- For study material: If NEXT is clicked, it should get marked as done

- For questions: Will be marked as done only when:

      1.  the question is answered correctly on the first attempt
      2.  the question is answered correct or wrong in the second attempt
      3.  see explanation is clicked
      4. (in short, we can say that whenever the explanation is displayed, the question will be marked as done)

https://user-images.githubusercontent.com/111858763/196968412-b448a030-46ce-4b1a-ae6e-d63c53501401.mp4

**Comment by kartiks26** [comment]
1.GET progressTracking/${courseId}/completedCourseContentIds
2. POST assessment/${exerciseId}/student/result

**Comment by kartiks26** [comment]
refactor/assesment
