### ISSUE TITLE
Volunteer Automation (Availability time)

### ISSUE THREAD

**Issue by Poonam-Singh-Bagh** [navgurukul/bhanwari-devi#796]
If the user doesn't select time, then the time state won't get updated and when the user completes the flow and click on `Go To Dashboard` button on the last page, the user will get an error.

**Comment by saquibaijaz** [comment]
1. The problem of mobile number verification is still there.
- The user verifies the mobile number and moves to the next page. If the user returns to the mobile verification screen, he cannot move forward without verifying the mobile number again.

2. If the time is not selected, and we go to the last screen of the flow, Clicking on the "Goto Dashboard" button gives an error, and according to the backend team, the error should be resolved by the frontend. (Check the screenshot for the error)

![image](https://user-images.githubusercontent.com/111858763/203548120-9f32221b-6840-410f-9fd7-b7bd6212b77d.png)

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh Please see above
